name: semantic-release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          GITHUB_TOKEN: b562ff58786628b33e9fad79ed9b2fc7d4dd1aaf
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npx semantic-release
